#!/usr/bin/env python3
"""Minify + gzip web/index.html and web/app.js, emit generated/web_assets.h.

Run manually, or via flash.py before every build. Keeps the HTML/JS/CSS
readable as separate source files under web/ while the firmware only ever
sees pre-compressed byte arrays it can stream straight from flash.
"""
import gzip
import re
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
WEB_DIR = PROJECT_DIR / "web"
OUT_FILE = PROJECT_DIR / "generated" / "web_assets.h"


def minify_html(html: str) -> str:
    html = re.sub(r"<!--.*?-->", "", html, flags=re.S)  # comments
    html = re.sub(r">\s+<", "><", html)  # whitespace between tags
    html = re.sub(r"^\s+", "", html, flags=re.M)  # leading indent per line
    return html.strip()


def minify_js(js: str) -> str:
    lines = []
    for line in js.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue  # drop blank lines and comment-only lines
        lines.append(stripped)
    return "\n".join(lines)


def to_c_array(name: str, data: bytes) -> str:
    body = ",".join(f"0x{b:02x}" for b in data)
    return (
        f"static const uint8_t {name}[] PROGMEM = {{{body}}};\n"
        f"static const size_t {name}_LEN = {len(data)};\n"
    )


def build_asset(src_path: Path, minify) -> tuple[bytes, int]:
    raw = src_path.read_text(encoding="utf-8")
    minified = minify(raw)
    gz = gzip.compress(minified.encode("utf-8"), compresslevel=9)
    return gz, len(raw)


def main():
    index_gz, index_raw_len = build_asset(WEB_DIR / "index.html", minify_html)
    app_js_gz, app_js_raw_len = build_asset(WEB_DIR / "app.js", minify_js)

    OUT_FILE.parent.mkdir(exist_ok=True)
    OUT_FILE.write_text(
        "// AUTO-GENERATED by scripts/build_web.py - do not edit by hand.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        + to_c_array("INDEX_HTML_GZ", index_gz)
        + "\n"
        + to_c_array("APP_JS_GZ", app_js_gz),
        encoding="utf-8",
    )

    print(f"index.html: {index_raw_len} -> {len(index_gz)} bytes gzipped")
    print(f"app.js:     {app_js_raw_len} -> {len(app_js_gz)} bytes gzipped")
    print(f"wrote {OUT_FILE.relative_to(PROJECT_DIR)}")


if __name__ == "__main__":
    main()
